package il.BAB08.db;


import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Date;

/*
 *
 * @author rpl a
 */
public class beranda extends javax.swing.JFrame {
//    Connection connect = koneksi.ordal();

    /**
     * Creates new form login
     */
    public beranda() {
        initComponents();
//        dataproduk();
//        tblbarang();
//        tblall();
//        tanggal();
//        tbljual();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        homebtn = new javax.swing.JButton();
        barangbtn = new javax.swing.JButton();
        detailbtn = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        exit1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        home = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        detail = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        barang = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        homebtn.setBackground(new java.awt.Color(255, 255, 255));
        homebtn.setText("HOME");
        homebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homebtnActionPerformed(evt);
            }
        });

        barangbtn.setBackground(new java.awt.Color(255, 255, 255));
        barangbtn.setText("BARANG");
        barangbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barangbtnActionPerformed(evt);
            }
        });

        detailbtn.setBackground(new java.awt.Color(255, 255, 255));
        detailbtn.setText("DETAIL PENJUALAN");
        detailbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailbtnActionPerformed(evt);
            }
        });

        exit.setBackground(new java.awt.Color(255, 0, 0));
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        exit1.setBackground(new java.awt.Color(255, 0, 0));
        exit1.setText("LOG OUT");
        exit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(detailbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(barangbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(homebtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(exit1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(homebtn)
                .addGap(18, 18, 18)
                .addComponent(barangbtn)
                .addGap(18, 18, 18)
                .addComponent(detailbtn)
                .addGap(18, 18, 18)
                .addComponent(exit1)
                .addGap(18, 18, 18)
                .addComponent(exit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new java.awt.CardLayout());

        home.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SELAMAT DATANG KASIR TERCINTA");

        jLabel2.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N

        javax.swing.GroupLayout homeLayout = new javax.swing.GroupLayout(home);
        home.setLayout(homeLayout);
        homeLayout.setHorizontalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homeLayout.createSequentialGroup()
                .addContainerGap(230, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(208, 208, 208))
        );
        homeLayout.setVerticalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel1)
                .addGap(70, 70, 70)
                .addComponent(jLabel2)
                .addContainerGap(458, Short.MAX_VALUE))
        );

        jPanel3.add(home, "card2");

        detail.setBackground(new java.awt.Color(255, 255, 255));

        jLabel13.setText("Detail ID");

        jLabel14.setText("Produk :");

        jLabel15.setText("Penjualan ID");

        jLabel16.setText("Jumlah Produk");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "==Pilih==" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jButton7.setText("Insert");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Update");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("hapus");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Penjualan", "Detail ID", "Produk ID", "Jumlah Produk", "Sub Total"
            }
        ));
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable3);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("Search");

        jTextField12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField12KeyReleased(evt);
            }
        });

        jLabel19.setText("Tanggal Jual");

        jLabel9.setText("SubTotal");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID Penjualan", "Tanggal Penjualan", "Total Harga"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jButton4.setText("Save");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText("Search");

        jTextField14.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField14KeyReleased(evt);
            }
        });

        jButton5.setText("sub");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel10.setText("Total Harga");

        jButton10.setText("Delete");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setText("ubah");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout detailLayout = new javax.swing.GroupLayout(detail);
        detail.setLayout(detailLayout);
        detailLayout.setHorizontalGroup(
            detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(detailLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane2)))
            .addGroup(detailLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(detailLayout.createSequentialGroup()
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField8))
                    .addGroup(detailLayout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField9))
                    .addGroup(detailLayout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField13))
                    .addGroup(detailLayout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(detailLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(detailLayout.createSequentialGroup()
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(detailLayout.createSequentialGroup()
                                .addGroup(detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addGap(18, 18, 18)
                                .addGroup(detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField11)
                                    .addGroup(detailLayout.createSequentialGroup()
                                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(detailLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37))
            .addGroup(detailLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel20)
                .addGap(18, 18, 18)
                .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        detailLayout.setVerticalGroup(
            detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField9)
                    .addGroup(detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField10)))
                .addGroup(detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(detailLayout.createSequentialGroup()
                        .addGroup(detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)))
                    .addGroup(detailLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5))))
                .addGap(18, 18, 18)
                .addGroup(detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)
                        .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(107, 107, 107)
                .addGroup(detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton8)
                    .addComponent(jButton9)
                    .addComponent(jLabel20)
                    .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10)
                    .addComponent(jButton11)
                    .addComponent(jButton4))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.add(detail, "card5");

        barang.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("MS Gothic", 1, 18)); // NOI18N
        jLabel3.setText("Produk ID");

        jLabel4.setFont(new java.awt.Font("MS Gothic", 1, 18)); // NOI18N
        jLabel4.setText("Nama Produk");

        jLabel5.setFont(new java.awt.Font("MS Gothic", 1, 18)); // NOI18N
        jLabel5.setText("Harga");

        jLabel6.setFont(new java.awt.Font("MS Gothic", 1, 18)); // NOI18N
        jLabel6.setText("Stok");

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setText("INSERT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setText("UPDATE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setText("DELETE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Produk ID", "Nama Produk", "Harga", "Stok"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel7.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        jLabel7.setText("Search");

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField5KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout barangLayout = new javax.swing.GroupLayout(barang);
        barang.setLayout(barangLayout);
        barangLayout.setHorizontalGroup(
            barangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 663, Short.MAX_VALUE)
            .addGroup(barangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(barangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(barangLayout.createSequentialGroup()
                        .addGroup(barangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(barangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1)
                            .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                            .addComponent(jTextField4))
                        .addGap(74, 74, 74)
                        .addComponent(jLabel8))
                    .addGroup(barangLayout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        barangLayout.setVerticalGroup(
            barangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barangLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(barangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(barangLayout.createSequentialGroup()
                        .addGroup(barangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField1))
                        .addGap(35, 35, 35)
                        .addGroup(barangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField2))
                        .addGap(27, 27, 27))
                    .addComponent(jLabel8))
                .addGap(7, 7, 7)
                .addGroup(barangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField3))
                .addGap(30, 30, 30)
                .addGroup(barangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 196, Short.MAX_VALUE)
                .addGroup(barangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jLabel7)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.add(barang, "card3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

//    public void tanggal() {
//        Date tgl = new Date();
//        jDateChooser1.setDate(tgl);
//        jTextField6.setEnabled(false);
//        jTextField7.setEnabled(false);
//        jTextField8.setEnabled(false);
//    }
//
//public void dataproduk(){
////        try {
////            String query = "SELECT * FROM produk";
////            Statement st = connect.createStatement();
////            ResultSet rs = st.executeQuery(query);
////            
////            while (rs.next()) {                
////                jComboBox2.addItem(rs.getString("ProdukID"));
////            }
////            
////            rs.last();
////            int jumlahdata = rs.getRow();
////            rs.first();
////            
////        } catch (SQLException e) {
////        }
//    }
//    private void tblbarang() {
//        // membuat tampilan model tabel
//        DefaultTableModel model = new DefaultTableModel();
//        model.addColumn("Produk ID");
//        model.addColumn("Nama Produk");
//        model.addColumn("Harga");
//        model.addColumn("Stok");
//
//        //menampilkan data database kedalam tabel
////        try {
////            String sql = "select * from produk";
////            java.sql.Statement stm = connect.createStatement();
////            java.sql.ResultSet res = stm.executeQuery(sql);
////            while (res.next()) {
////                model.addRow(new Object[]{res.getString(1), res.getString(2), res.getString(3), res.getString(4)});
////            }
////            jTable1.setModel(model);
////        } catch (Exception e) {
////        }
//
//    }
//
//    private void tblall() {
//         DefaultTableModel model = new DefaultTableModel();
//        model.addColumn("Detail ID");
//        model.addColumn("Penjualan ID");
//        model.addColumn("Produk ID");
//        model.addColumn("Jumlah Produk");
//        model.addColumn("Sub Total");
//        jTable3.setModel(model);
////        try {
////            Statement state = connect.createStatement();
////            ResultSet data = state.executeQuery("select * from  detail_penjualan");
////            while (data.next()) {
////                model.addRow(new Object[]{
////                    data.getString("DetailID"),
////                    data.getString("PenjualanID"),
////                    data.getString("ProdukID"),
////                    data.getString("JumlahProduk"),
////                    data.getString("SubTotal")
////                });
////                jTable3.setModel(model);
////            }
////        } catch (Exception e) {
////            System.err.println("Terjadi Kesalahan" + e);	 }
////    }
////
////     private void tbljual() {
////        // membuat tampilan model tabel
////        DefaultTableModel model = new DefaultTableModel();
////        model.addColumn("ID Penjualan");
////        model.addColumn("Tanggal Penjualan");
////        model.addColumn("Total Harga");
////
////        //menampilkan data database kedalam tabel
////       jTable2.setModel(model);
////        try {
////            Statement state = connect.createStatement();
////            ResultSet data = state.executeQuery("select * from penjualan");
////            while (data.next()) {
////                model.addRow(new Object[]{
////                    data.getString("PenjualanID"),
////                    data.getString("TanggalPenjualan"),
////                    data.getString("TotalHarga")
////                });
////                jTable2.setModel(model);
////            }
////        } catch (Exception e) {
////            System.err.println("Terjadi Kesalahan" + e);
////    }
//     }
    
    

    private void homebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homebtnActionPerformed
        home.setVisible(true);
        barang.setVisible(false);
        detail.setVisible(false);
    }//GEN-LAST:event_homebtnActionPerformed

    private void barangbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barangbtnActionPerformed
        home.setVisible(false);
        barang.setVisible(true);
        detail.setVisible(false);
    }//GEN-LAST:event_barangbtnActionPerformed

    private void detailbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailbtnActionPerformed
        home.setVisible(false);
        barang.setVisible(false);
        detail.setVisible(true);
    }//GEN-LAST:event_detailbtnActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//        try {
//            String sql = "INSERT INTO produk VALUES ('" + jTextField1.getText() + "','" + jTextField2.getText() + "','" + jTextField3.getText() + "','" + jTextField4.getText() + "')";
////            java.sql.PreparedStatement pst = connect.prepareStatement(sql);
////            pst.execute();
//            JOptionPane.showMessageDialog(null, "Penyimpanan Data Berhasil");
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(this, e.getMessage());
//        }
//        jTextField1.setText("");
//        jTextField2.setText("");
//        jTextField3.setText("");
//        jTextField4.setText("");
//        tblbarang();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
//        int baris = jTable1.rowAtPoint(evt.getPoint());
//        String ProdukID = jTable1.getValueAt(baris, 0).toString();
//        jTextField1.setText(ProdukID);
//        String NamaProduk = jTable1.getValueAt(baris, 1).toString();
//        jTextField2.setText(NamaProduk);
//
//        String Harga = jTable1.getValueAt(baris, 2).toString();
//        jTextField3.setText(Harga);
//        String Stok = jTable1.getValueAt(baris, 3).toString();
//        jTextField4.setText(Stok);
//
//        jTextField1.setEnabled(false);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
//        try {
//            String sql = "UPDATE produk SET ProdukID = '" + jTextField1.getText() + "', NamaProduk = '" + jTextField2.getText() + "', Harga = '" + jTextField3.getText() + "',Stok= '" + jTextField4.getText() + "' WHERE ProdukID = '" + jTextField1.getText() + "'";
////            java.sql.PreparedStatement pst = connect.prepareStatement(sql);
////          pst.execute();
//            JOptionPane.showMessageDialog(null, "data berhasil di edit");
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, "Perubahan Data Gagal" + e.getMessage());
//        }
//        tblbarang();
//        jTextField1.setText("");
//        jTextField2.setText("");
//        jTextField3.setText("");
//        jTextField4.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
//////        try {
//////            String sql = "delete from produk where ProdukID='" + jTextField1.getText() + "'";
////////            java.sql.PreparedStatement pst = connect.prepareStatement(sql);
////////            pst.execute();
//////            JOptionPane.showMessageDialog(this, "berhasil di hapus");
//////        } catch (Exception e) {
//////            JOptionPane.showMessageDialog(this, e.getMessage());
//////        }
//////        tblbarang();
//////        jTextField1.setText("");
//////        jTextField2.setText("");
//////        jTextField3.setText("");
//////        jTextField4.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyReleased
//       String search = jTextField5.getText();
//        DefaultTableModel model = new DefaultTableModel();
//        model.addColumn("Produk ID");
//        model.addColumn("Nama Produk");
//        model.addColumn("Harga");
//        model.addColumn("Stok");
//        jTable1.setModel(model);
//        try {
////            Statement cari = connect.createStatement();
//            ResultSet data = cari.executeQuery("select * from produk  where  ProdukID like '%"
//                    + search +  "%' or NamaProduk like '%"
//                    + search + "%' or Harga like '%" + search + "%' or Stok like '%" + search +"%'");
//            while (data.next()) {
//                model.addRow(new Object[]{
//                    data.getString("ProdukID"),
//                    data.getString("NamaProduk"),
//                    data.getString("Harga"),
//                    data.getString("Stok")
//                });
//                jTable1.setModel(model);
//            }
//        } catch (Exception e) {
//            System.err.println("Terjadi kesalahan" + e);
//        }
    }//GEN-LAST:event_jTextField5KeyReleased

    private void jTextField12KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField12KeyReleased
//       String search = jTextField12.getText();
//        DefaultTableModel model = new DefaultTableModel();
//        model.addColumn("Detail ID");
//        model.addColumn("Penjualan ID");
//        model.addColumn("Produk ID");
//        model.addColumn("Jumlah Produk");
//        model.addColumn("Sub Total");
//        jTable3.setModel(model);
//        try {
//            Statement cari = connect.createStatement();
//            ResultSet data = cari.executeQuery("select * from detail_penjualan  where  DetailID like '%"
//                    + search +  "%' or PenjualanID like '%"
//                    + search + "%' or ProdukID like '%" + search + "%' or JumlahProduk like '%" + search + "%' or SubTotal like '%" + search + "%'");
//            while (data.next()) {
//                model.addRow(new Object[]{
//                    data.getString("DetailID"),
//                    data.getString("PenjualanID"),
//                    data.getString("ProdukID"),
//                    data.getString("JumlahProduk"),
//                    data.getString("SubTotal")
//                });
//                jTable3.setModel(model);
//            }
//        } catch (Exception e) {
//            System.err.println("Terjadi kesalahan" + e);
//        }
    }//GEN-LAST:event_jTextField12KeyReleased

    private void exit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit1ActionPerformed
// login panggil = new login();
//panggil.show();
    }//GEN-LAST:event_exit1ActionPerformed

    private void jTextField14KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField14KeyReleased
//       String search = jTextField14.getText();
//        DefaultTableModel model = new DefaultTableModel();
//        model.addColumn("ID Penjualan");
//        model.addColumn("Tanggal Penjualan");
//        model.addColumn("Total Harga");
//
//        jTable2.setModel(model);
//        try {
//            Statement cari = connect.createStatement();
//            ResultSet data = cari.executeQuery("select * from penjualan  where  PenjualanID like '%"
//                    + search +  "%' or TanggalPenjualan like '%"
//                    + search + "%' or TotalHarga like '%" + search +"%'");
//            while (data.next()) {
//                model.addRow(new Object[]{
//                    data.getString("PenjualanID"),
//                    data.getString("TanggalPenjualan"),
//                    data.getString("TotalHarga")
//                });
//                jTable2.setModel(model);
//            }
//        } catch (Exception e) {
//            System.err.println("Terjadi kesalahan" + e);
//        }
    }//GEN-LAST:event_jTextField14KeyReleased

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
double harga = Double.parseDouble(jTextField8.getText());
int jumlah = Integer.parseInt(jTextField10.getText());
double total  =harga * jumlah;
jTextField6.setText(String.valueOf(total));
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
//try {
//Statement stat = connect.createStatement();
//            ResultSet data = stat.executeQuery("select * from produk where ProdukID ='" + jComboBox2.getSelectedItem() + "'");
//            if (data.next()){
//            jTextField7.setText(data.getString("NamaProduk"));
//            jTextField8.setText(data.getString("Harga"));
//            }
//}catch (Exception e) {
//            System.err.println("Terjadi kesalahan" + e);
//        }
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
//        try {
//            Statement stat = connect.createStatement();
//            ResultSet data = stat.executeQuery("select * from detail_penjualan where DetailID ='" + jTextField9.getText() + "'");
//            if (data.next()) {
//                JOptionPane.showMessageDialog(null, "ID Detail Penjualan sudah ada!!!", "PERHATIAN", JOptionPane.WARNING_MESSAGE);
//                jTextField9.requestFocus();
//            } 
//            else if (jTextField9.getText().equals("") || jTextField13.getText().equals("") 
//                    || jTextField10.getText().equals("")|| jTextField6.getText().equals("") || jComboBox2.getSelectedItem().equals("Pilih")) 
//            {
//                JOptionPane.showMessageDialog(null, "Data tidak boleh kosong!!!", "PERHATIAN", JOptionPane.WARNING_MESSAGE);
//            } 
//            else{
//                SimpleDateFormat fm = new SimpleDateFormat("yyyy-MM-dd");
//                String tglbeli = String.valueOf(fm.format(jDateChooser1.getDate()));
//                String sql = "insert into detail_penjualan values ('" + jTextField9.getText() + "'"
//                        + ",'" + jTextField13.getText() + "'"
//                        + ",'" + jComboBox2.getSelectedItem() + "'"
//                        + ",'" + jTextField10.getText() + "'"
//                        + ",'" + jTextField6.getText() + "')";
//                stat.executeUpdate(sql);
//                jTextField13.setText("");
//                jTextField9.setText("");
//                jTextField10.setText("");
//                jTextField6.setText("");
//                jComboBox2.setSelectedIndex(0);
//                JOptionPane.showMessageDialog(null, "Data Berhasil di input!!!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
//                tblall();
//            }
//            stat.close();
//        } catch (Exception exc) {
//            System.err.println("Terjadi Kesalahan  : " + exc);
//        }
//        jTextField7.setText("");
//        jTextField8.setText("");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
//        try {
//            Statement stat = connect.createStatement();
//            ResultSet data = stat.executeQuery("select * from penjualan where PenjualanID ='" + jTextField13.getText() + "'");
//            if (data.next()) {
//                JOptionPane.showMessageDialog(null, "ID Penjualan sudah ada!!!", "PERHATIAN", JOptionPane.WARNING_MESSAGE);
//                jTextField13.requestFocus();
//            } 
//            else if (jTextField9.getText().equals("") || jTextField13.getText().equals("") 
//                    || jTextField7.getText().equals("")|| jTextField6.getText().equals("") || jComboBox2.getSelectedItem().equals("Pilih")|| jDateChooser1.getDate()==null 
//                    || jTextField11.getText().equals("")) 
//            {
//                JOptionPane.showMessageDialog(null, "Data tidak boleh kosong!!!", "PERHATIAN", JOptionPane.WARNING_MESSAGE);
//            } 
//            else{
//                SimpleDateFormat fm = new SimpleDateFormat("yyyy-MM-dd");
//                String tglbeli = String.valueOf(fm.format(jDateChooser1.getDate()));
//                String sql = "insert into penjualan values ('" + jTextField13.getText() + "'"
//                        + ",'" + tglbeli + "'"
//                        + ",'" + jTextField6.getText() + "')";
//                stat.executeUpdate(sql);
//                String pollo = "insert into detail_penjualan values ('" + jTextField9.getText() + "'"
//                        + ",'" + jTextField13.getText() + "'"
//                        + ",'" + jComboBox2.getSelectedItem() + "'"
//                        + ",'" + jTextField10.getText() + "'"
//                        + ",'" + jTextField6.getText() + "')";
//                stat.executeUpdate(pollo);
//                 jTextField13.setText("");
//                jTextField9.setText("");
//                jTextField10.setText("");
//                jTextField6.setText("");
//                jComboBox2.setSelectedIndex(0);
//                jTextField11.setText("");
//                JOptionPane.showMessageDialog(null, "Data Berhasil di input!!!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
//                tbljual();
//                tblall();
//            }
//            stat.close();
//        } catch (Exception exc) {
//            System.err.println("Terjadi Kesalahan  : " + exc);
//        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
//try {
//            String sql ="UPDATE detail_penjualan SET PenjualanID = '"+jTextField13.getText()+"', ProdukID = '"+ jComboBox2.getSelectedItem()
//+"', JumlahProduk = '"+jTextField10.getText()
//+"',SubTotal= '"+ jTextField6.getText()
//+"' WHERE DetailID = '"+ jTextField9.getText()+"'";
//            java.sql.Connection conn=(Connection)config.configDB();
//            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
//            pst.execute();
//            JOptionPane.showMessageDialog(null, "data berhasil di edit");
//             jTextField13.setText("");
//                jTextField10.setText("");
//                jTextField6.setText("");
//                jTextField9.setText("");
//                jTextField7.setText("");
//                jTextField8.setText("");
//                jComboBox2.setSelectedIndex(0);
//                jTextField9.enable(true);
//                jTextField9.requestFocus();
//                tblall();
//
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, "Perubahan Data Gagal"+ e.getMessage());
//        }

    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
//if (jTextField13.getText().equals("") || jTextField11.getText().equals("") ||jDateChooser1.getDate()==null)
//       {
//       JOptionPane.showMessageDialog(null, "Silahkan Pilih data yang akan di Update!!!", "PERHATIAN!!!!",JOptionPane.WARNING_MESSAGE);
//       }
//       else {
//        int ok = JOptionPane.showConfirmDialog(null, "Apakah yakin ingin Update data ini?", "Konfirmasi Dialog", JOptionPane.YES_NO_OPTION);
//        if (ok == 0) {
//            try {
//                SimpleDateFormat fm = new SimpleDateFormat("yyyy-MM-dd");
//                String tglbeli = String.valueOf(fm.format(jDateChooser1.getDate()));
//                String sql = "update penjualan set TanggalPenjualan ='" + tglbeli
//                        + "', TotalHarga ='" + jTextField11.getText()
//                        + "' where PenjualanID='" + jTextField13.getText().trim() + "'";
//                Statement stat = connect.createStatement();
//                stat.executeUpdate(sql);
//                JOptionPane.showMessageDialog(null, "Data Berhasil dirubah!!!", "Ubah Data", JOptionPane.INFORMATION_MESSAGE);
//                stat.close();
//                jTextField13.setText("");
//                jTextField11.setText("");
//                jTextField13.enable(true);
//                jTextField13.requestFocus();
//                tbljual();
//            } catch (Exception e) {
//                JOptionPane.showMessageDialog(null, "Perubahan data gagal" + e.getMessage());
//            }
//        }
//        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
// if(jTextField13.getText().equals("") || jTextField11.getText().equals("") 
//                    ||jDateChooser1.getDate()==null) {
// JOptionPane.showMessageDialog(null, "Silahkan pilih data yang dihapus!!!","Perhatian!!", JOptionPane.WARNING_MESSAGE);
// }
// else {
//        int ok = JOptionPane.showConfirmDialog(null, "Apakah yakin ingin Hapus data ini?", "Konfirmasi Dialog", JOptionPane.YES_NO_OPTION);
//        if (ok == 0) {
//            String sql = "delete from penjualan where PenjualanID='" + jTextField13.getText().trim() + "'";
//            try {
////                Statement stat = connect.createStatement();
////                stat.executeUpdate(sql);
//                JOptionPane.showMessageDialog(null, "Data Berhasil dihapus!!!", "Hapus Data", JOptionPane.INFORMATION_MESSAGE);
////                stat.close();
//                jTextField13.setText("");
//                jTextField11.setText("");
//                jTextField13.enable(true);
//                jTextField13.requestFocus();
////                tbljual();
////            } catch (SQLException exc) {
//                System.err.println(sql);
////                System.err.println("error" + exc);
//            }
//       }
// }}
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
//try
//{ 
// SimpleDateFormat fm = new SimpleDateFormat("yyyy-MM-dd");
// int baris = jTable2.getSelectedRow();
//
//if (baris !=1)
//{
//jTextField13.setText(jTable2.getValueAt(baris, 0).toString());
//jDateChooser1.setDate(fm.parse(jTable2.getValueAt(baris, 1).toString()));
//jTextField11.setText(Double.toString(Double.parseDouble(jTable2.getValueAt(baris, 2).toString())));
//}jTextField13.enable(false);
//} catch (Exception exc) {
//System.err.println("Terjadi Kesalahan: " + exc);}
    }//GEN-LAST:event_jTable2MouseClicked

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
//try
//{ 
// SimpleDateFormat fm = new SimpleDateFormat("yyyy-MM-dd");
// int baris = jTable3.getSelectedRow();
//
//if (baris !=1)
//{
//jTextField13.setText(jTable3.getValueAt(baris, 0).toString());
//jTextField9.setText(jTable3.getValueAt(baris, 1).toString());
//jComboBox2.setSelectedItem(jTable3.getValueAt(baris, 2).toString());
//jTextField10.setText(jTable3.getValueAt(baris, 3).toString());
//jTextField6.setText(Double.toString(Double.parseDouble(jTable3.getValueAt(baris, 4).toString())));
//}jTextField13.enable(false);
//jTextField9.enable(false);
//} catch (Exception exc) {
//System.err.println("Terjadi Kesalahan: " + exc);}
    }//GEN-LAST:event_jTable3MouseClicked

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
// if(jTextField9.getText().equals("") || jTextField13.getText().equals("")  || jComboBox2.getSelectedItem().equals("Pilih")
//                    ||jTextField10.getText().equals("")|| jTextField6.getText().equals("")) {
// JOptionPane.showMessageDialog(null, "Silahkan pilih data yang dihapus!!!","Perhatian!!", JOptionPane.WARNING_MESSAGE);
// }
// else {
//        int ok = JOptionPane.showConfirmDialog(null, "Apakah yakin ingin Hapus data ini?", "Konfirmasi Dialog", JOptionPane.YES_NO_OPTION);
//        if (ok == 0) {
//            String sql = "delete from detail_penjualan where DetailID='" + jTextField13.getText().trim() + "'";
//            try {
//                Statement stat = connect.createStatement();
//                stat.executeUpdate(sql);
//                JOptionPane.showMessageDialog(null, "Data Berhasil dihapus!!!", "Hapus Data", JOptionPane.INFORMATION_MESSAGE);
//                stat.close();
//                jTextField13.setText("");
//                jTextField9.setText("");
//                jComboBox2.setSelectedIndex(0);
//                jTextField10.setText("");
//                jTextField6.setText("");
//                jTextField9.setEnabled(true);
//                jTextField13.enable(true);
//                jTextField13.requestFocus();
//                tblall();
//            } catch (SQLException exc) {
//                System.err.println(sql);
//                System.err.println("error" + exc);
//            }
//        }
// }
    }//GEN-LAST:event_jButton10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new beranda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barang;
    private javax.swing.JButton barangbtn;
    private javax.swing.JPanel detail;
    private javax.swing.JButton detailbtn;
    private javax.swing.JButton exit;
    private javax.swing.JButton exit1;
    private javax.swing.JPanel home;
    private javax.swing.JButton homebtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
